### ISSUE TITLE
v0.4.1.3 can't find source for Numeric/GSL/Distribution/Internal in lib

### ISSUE THREAD

**Issue by jimstutt** [amcphail/hmatrix-gsl-stats#11]
It was there in v0.4.

**Comment by amcphail** [comment]
There is something wrong with the git repository.

Hackage v04.1.3 has the Internal.hs file.

I'm looking into this.

**Comment by amcphail** [comment]
Uploaded Internal.hs

Something strange happened to my local git repository.
