### ISSUE TITLE
Build fail on ghc-7.8.4

### ISSUE THREAD

**Issue by jimstutt** [amcphail/hmatrix-gsl-stats#4]
ghc-7.8.4 can't find gsl on Nixos-14.12 x86_64. I have gsl headers and lib installed in /usr/local/include and /usr/local.lib; -extra-include-dirs and --extra-lib-dirs flags are being ignored if I add them.
Looking on hydra the builds started failing with ghc-7.8.4  I get the same msg as:

http://hydra.nixos.org/build/18786082/nixlog/1

Checking foreign libraries... FAIL
77 *** Sorry, I can't link GSL.
78 *** Please make sure that the appropriate -dev packages are installed.
79 *** You can also specify the required libraries using
80 *** cabal install hmatrix-gsl-stats --configure-option=link:lib1,lib2,lib3,etc.
81building
82Setup: Package hmatrix-gsl-stats-0.2 can't be built on this system.
83builder for ‘/...-haskell-hmatrix-gsl-stats-0.2.drv’ failed with exit code 1pThis 
Checking foreign libraries... FAIL
77 *** Sorry, I can't link GSL.
78 *** Please make sure that the appropriate -dev packages are installed.
79 *** You can also specify the required libraries using
80 *** cabal install hmatrix-gsl-stats --configure-option=link:lib1,lib2,lib3,etc.
81building
82Setup: Package hmatrix-gsl-stats-0.2 can't be built on this system.
83builder for ‘/...-haskell-hmatrix-gsl-stats-0.2.drv’ failed with exit code 1

**Comment by amcphail** [comment]
Is this file on your system in a findable location?

#include <gsl/gsl_sf_gamma.h>

**Comment by amcphail** [comment]
`#include <gsl/gsl_sf_gamma.h>`

**Comment by amcphail** [comment]
`#include <gsl/gsl_sf_exp.h>`

**Comment by amcphail** [comment]
Are either of these files on your system in a findable location?

#include <gsl/gsl_sf_gamma.h>

#include <gsl/gsl_sf_exp.h>

**Comment by amcphail** [comment]
This patch, 820e40d, changes the build method for finding libraries (it doesn't anymore.  Just like hmatrix).

**Comment by jimstutt** [comment]
I pulled you new upload 0.2.1 from git. I have both headers available but with their path as an --extra-include-dirs  I have a problem with double.h.

Created temporary directory: /run/user/1000/ghc23348_0
*** C Compiler:
/nix/store/w1lj2s6v2wjmgd44fdi9i1p53qbxrqdc-gcc-wrapper-4.8.3/bin/gcc -fno-stack-protector -DTABLES_NEXT_TO_CODE -O4 -msse2 -Wall -fPIC -O2 -x c lib/Numeric/GSL/statistics-aux.c -o /run/user/1000/ghc23348_0/ghc23348_1.s -Wimplicit -S '-D__GLASGOW_HASKELL__=708' -Idist/build/autogen -Idist/build -I/nix/store/l59kfcm2bsrp4hadhzgr4lmk900hkcma-gsl-1.16/include/gsl -I/nix/store/85ac5rpj9vc9l2w7hgb40wa5h6s5aac1-haskell-vector-ghc7.8.3-0.10.12.1-shared/lib/ghc-7.8.3/vector-0.10.12.1/include -I/nix/store/kckfb0hki6hrr6pkfpdqcmk8bdsnfzb8-haskell-primitive-ghc7.8.3-0.5.4.0-shared/lib/ghc-7.8.3/primitive-0.5.4.0/include -I/nix/store/4yn5j14b3650lsdka16x30z1inmbpnyl-ghc-7.8.3/lib/ghc-7.8.3/time-1.4.2/include -I/nix/store/4yn5j14b3650lsdka16x30z1inmbpnyl-ghc-7.8.3/lib/ghc-7.8.3/bytestring-0.10.4.0/include -I/nix/store/4yn5j14b3650lsdka16x30z1inmbpnyl-ghc-7.8.3/lib/ghc-7.8.3/base-4.7.0.1/include -I/nix/store/z39i96sah6h4s5392riwxbq1yksrchi4-gmp-5.1.3/include -I/nix/store/4yn5j14b3650lsdka16x30z1inmbpnyl-ghc-7.8.3/lib/ghc-7.8.3/integer-gmp-0.5.1.0/include -I/nix/store/4yn5j14b3650lsdka16x30z1inmbpnyl-ghc-7.8.3/lib/ghc-7.8.3/include

lib/Numeric/GSL/statistics-aux.c:1:39:
     fatal error: gsl/gsl_statistics_double.h: No such file or directory
     #include <gsl/gsl_statistics_double.h>
                                           ^
compilation terminated.
 
Tnx for the fast response. I don't know whether the etiquette is to reopen when the issue isn't resolved?

**Comment by jimstutt** [comment]
I invoked it with both gsl-1.16/include and gsl-1.16/include/gsl in the --extras

>    cabal install --extra-include-dirs=/nix/store/l59kfcm2bsrp4hadhzgr4lmk900hkcma-gsl-1.16/include/:/nix-store/l59kfcm2bsrp4hadhzgr4lmk900hkcma-gsl-1.16/include/gsl --extra-lib-dirs=/nix/store/l59kfcm2bsrp4hadhzgr4lmk900hkcma-gsl-1.16/lib -v3

**Comment by jimstutt** [comment]
Both gsl/gsl_statistics_double h  and /lib/Numeric/gsl/GSL/statistics-aux.c exist in seemingly the correct path.

**Comment by amcphail** [comment]
Hi,

Thanks for your reply.

If the issue isn't resolved then by all means reopen it.

I'm looking into this some more.

Cheers,

Vivian

**Comment by amcphail** [comment]
Hi Jim,

Does `hmatrix` install successfully on your system?


Vivian
